services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ../mosquitto/config:/mosquitto/config
      - ../mosquitto/data:/mosquitto/data
      - ../mosquitto/log:/mosquitto/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "$$SYS/#", "-C", "1"]
      interval: 10s
      timeout: 5s
      retries: 5

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    user: "1000:1000"
    env_file: .env
    volumes:
      - type: bind
        source: ../telegraf/telegraf.conf
        target: /etc/telegraf/telegraf.conf
      - type: bind
        source: ../telegraf/
        target: /var/log/telegraf
    depends_on:
      influxdb3:
        condition: service_healthy
      mosquitto:
        condition: service_healthy

  influxdb3:
    image: influxdb:3-core
    container_name: influxdb3
    user: "1000:1000"
    ports:
      - "8181:8181"
    volumes:
      - type: bind
        source: ../influxdb3/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: ../influxdb3/plugins
        target: /var/lib/influxdb3/plugins
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
      - --disable-authz=health

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  explorer:
    image: influxdata/influxdb3-ui:1.2.0
    container_name: influxdb3-explorer
    pull_policy: always
    command: ["--mode=admin"]
    ports:
      - "8888:80"


  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - /var/log:/var/log
    ports:
      - "3100:3100"
    command: 
      -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    
  portainer:
    image: portainer:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Give Portrainer access to docker
      - ./portrainer/data:/data
    restart: unless-stopped

volumes:
  grafana-storage:
