[agent]
  interval = "10s"
  round_interval = true
  debug = true
  quiet = false

# Input: MQTT consumer
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics  = ["airnode-00/state"]       # change this to match your MQTT topic
  qos = 0
  data_format = "json"

# Output: InfluxDB v2
[[outputs.influxdb_v2]]
  urls = ["http://influxdb3:8181"]  # use your InfluxDB hostname + port
  token = "${INFLUXDB_TELEGRAF_TOKEN}"
  organization = "default"
  bucket = "metrics"
